### ISSUE TITLE
Opening up the DVSA component library

### ISSUE THREAD

**Issue by MartinDM** [dvsa/front-end#178]
Since other Gov't service digital teams (such as Home Office) make their component systems available publicly, should we also consider doing the same for our library too, if not the prototypes themselves?

**This would**
...mean we can reference components in the system and provide working links to them, and allow them to be used by other teams.

Allow MOT components to be adapted for other teams with similar use cases as the 'MOT-only' notice might be a bit restrictive if there's a use case for others.

Allow us to expand what we have alongside the component library to include other resources, publish research findings and notes?

Thoughts?

**Ref: Home Office Design system**
https://home-office-digital-patterns.herokuapp.com/components

**Comment by MartinDM** [comment]
Added the login credentials to Readme

**Comment by rafaldrewnowski** [comment]
Opening library section - absolutely yes. Prototypes should remain locked.

**Comment by nickharewood** [comment]
This seems consistent with other .gov Design Systems - @MartinDM how much effort is involved to restructure to separate prototypes from library?

**Comment by MartinDM** [comment]
Closing issue as Password is now set for Prototypes only.
[DVSA Design system](https://dvsa-front-end.herokuapp.com/library/mts) now available for anyone to easily access without any login.

Prototypes are still shared using the Credentials on the README.
